version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
